import { defineSchema, defineTable } from "convex/server";
import { authTables } from "@convex-dev/auth/server";
import { v } from "convex/values";

/**
 * Beyond the Black Box - Database Schema
 * --------------------------------------
 * This schema defines the structure of our cloud database.
 * We use strict validation to ensure bad data never enters the system.
 */

export default defineSchema({
  // 1. Authentication Tables (Google Login)
  // Provided automatically by @convex-dev/auth. Includes 'users', 'sessions', 'accounts'.
  ...authTables,

  // 2. Citizen Reports
  // Crowdsourced reports from users regarding power grid issues.
  citizen_reports: defineTable({
    userId: v.optional(v.id("users")), // Can be null if we allow anonymous reports
    cityId: v.string(),                // e.g., "lucknow", "noida"
    
    // Categorizing the problem
    reportType: v.union(
      v.literal("outage"), 
      v.literal("voltage_fluctuation"), 
      v.literal("sparking"),
      v.literal("infrastructure_damage")
    ),
    description: v.string(),
    
    // Optional precise location
    lat: v.optional(v.float64()),
    lon: v.optional(v.float64()),
    
    // Verification lifecycle
    status: v.union(
      v.literal("pending"), 
      v.literal("verified"), 
      v.literal("resolved")
    ),
  })
    .index("by_city", ["cityId"])
    .index("by_status", ["status"])
    .index("by_user", ["userId"]),

  // 3. AI Risk Predictions
  // Stores the output from our Python ML service for each city.
  // The web dashboard subscribes to this table for real-time updates.
  predictions: defineTable({
    cityId: v.string(),
    timestamp: v.number(), // Epoch time of the prediction
    
    // Risk Metrics
    riskLevel: v.union(
      v.literal("LOW"), 
      v.literal("MODERATE"), 
      v.literal("HIGH"), 
      v.literal("CRITICAL")
    ),
    rawRisk: v.float64(),
    adjustedRisk: v.float64(),
    rainAdjustmentApplied: v.boolean(),
    
    // Plain English Explainability (Generated by Python)
    explanation: v.object({
      summary: v.string(),
      factors: v.array(
        v.object({
          feature: v.string(),
          label: v.string(),
          value: v.float64(),
          impact: v.union(v.literal("low"), v.literal("medium"), v.literal("high")),
          explanation: v.string(),
        })
      ),
    }),
  })
    .index("by_city_and_time", ["cityId", "timestamp"]),

  // 4. Weather Cache
  // Stores hourly historical weather data for rolling averages (required by the ML model).
  weather_cache: defineTable({
    cityId: v.string(),
    timestamp: v.number(),
    
    // Only storing what we actually need for the 24h rolling averages
    temperature_2m: v.float64(),
    surface_pressure: v.float64(),
  })
    .index("by_city_and_time", ["cityId", "timestamp"]),
});
